import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Password Generator",
  description: "Generated by create next app",
  icons: [
    {
      url: "./favicons/favicon-red.ico",
      media: "(prefers-color-scheme: light)",
    },
    {
      url: "./favicons/favicon-white.ico",
      media: "(prefers-color-scheme: dark)",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>{children}</body>
    </html>
  );
}
